# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph.proto',
  package='graph',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgraph.proto\x12\x05graph\"<\n\x0eNodeAttributes\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\"/\n\x0e\x45\x64geAttributes\x12\x0e\n\x06weight\x18\x01 \x01(\x02\x12\r\n\x05since\x18\x02 \x01(\tb\x06proto3'
)




_NODEATTRIBUTES = _descriptor.Descriptor(
  name='NodeAttributes',
  full_name='graph.NodeAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='graph.NodeAttributes.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='graph.NodeAttributes.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='graph.NodeAttributes.active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=82,
)


_EDGEATTRIBUTES = _descriptor.Descriptor(
  name='EdgeAttributes',
  full_name='graph.EdgeAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='graph.EdgeAttributes.weight', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='since', full_name='graph.EdgeAttributes.since', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['NodeAttributes'] = _NODEATTRIBUTES
DESCRIPTOR.message_types_by_name['EdgeAttributes'] = _EDGEATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeAttributes = _reflection.GeneratedProtocolMessageType('NodeAttributes', (_message.Message,), {
  'DESCRIPTOR' : _NODEATTRIBUTES,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.NodeAttributes)
  })
_sym_db.RegisterMessage(NodeAttributes)

EdgeAttributes = _reflection.GeneratedProtocolMessageType('EdgeAttributes', (_message.Message,), {
  'DESCRIPTOR' : _EDGEATTRIBUTES,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:graph.EdgeAttributes)
  })
_sym_db.RegisterMessage(EdgeAttributes)


# @@protoc_insertion_point(module_scope)
